### ISSUE TITLE
Create Desktop ICONS for RITE 

### ISSUE THREAD

**Issue by pauls4GE** [ge-high-assurance/RITE#115]
![Capture](https://github.com/ge-high-assurance/RITE/assets/66636651/430a1840-e9de-4046-a9bb-a476e637790f)

Use the above image

**Comment by pauls4GE** [comment]
Add this to the dev branch https://github.com/ge-high-assurance/RITE/tree/dev when done @davidcok

**Comment by davidcok** [comment]
Fixed with the merge of the dev branch.
