### ISSUE TITLE
Add a button to stop console processing for RACK/IDE console

### ISSUE THREAD

**Issue by baoluomeng** [ge-high-assurance/RITE#13]

**Comment by chrisage** [comment]
Related: https://github.com/ge-high-assurance/RITE/issues/16

**Comment by saratge** [comment]
https://github.com/ge-high-assurance/RITE/commit/6bb47137ed2c1996aa6e055d2f1e697495074b1a
Tracking Progress Monitor status to check if it is cancelled, if it is indeed cancelled using the stop button on Eclipse Progress Monitor

**Comment by baoluomeng** [comment]
Is the stop button visible to user? or user can only see it when the progress monitor is on a separate view?

**Comment by saratge** [comment]
Right now, the stop button is only on the progress monitor, should come up with the right way to program the eclipse platform api to have the stop button on the console toolbar

**Comment by saratge** [comment]
We can take VERDICT approach, I think there must be an easier way by using the Eclipse Platform API than creating a separate Stop handler

**Comment by baoluomeng** [comment]
Okay, then. Let's reopen this issue and push it to the next milestone.

**Comment by baoluomeng** [comment]
Alternatively, you can open the progress monitor view by default (if there is a way to do this) so that user can see the stop button and use it.

**Comment by saratge** [comment]
Now by default, I show the Progress View
