### ISSUE TITLE
Source Dependencies in Ingestion Package ZIP and Upload function

### ISSUE THREAD

**Issue by baoluomeng** [ge-high-assurance/RITE#14]
**Background**:
Currently ingestion packages are built from content of a folder e.g. All files are zipped up and uploaded. There are cases where an overlay depends on core models from a separate package. We need to enhance the upload as ingestion package upload functionality to scan for and include dependencies in the generated ingestion package.

**Acceptance Criteria**:
Extend existing upload as ingestion package functionality to scan and include project dependencies when generating an ingestion package.

**Implementation Details**:

- Port the [Ingestion Package Generation functionality from the RACK CLI](https://github.com/ge-high-assurance/RACK/blob/6dfcc71a2538a429ac9cadea9db78f99df94a769/cli/rack/__init__.py#L353)
- The Rack IPG works by:
    - 1. collecting references to all RACK resources between projects (and sub-projects), 
    - 2. collecting all manifest graph references
    - 3. organize the project into a flat structure, with newly created (indexed) folder names 
    - 4. recreating the manifest based on the flat structure and combined graph references
- The resulting ingestion package will only have a manifest at the top level, and ordered sub folders for resources based on type (model, data, nodegorups etc.)

**Comment by baoluomeng** [comment]
This depends on the modular project creation features.

**Comment by chrisage** [comment]
@baoluomeng would there ever be a use case for not including ingestion project dependencies when generating/uploading an ingestion package?

**Comment by chrisage** [comment]
Related to https://github.com/ge-high-assurance/RITE/issues/10 https://github.com/ge-high-assurance/RITE/blob/dasc23DO178C/tools/rack/rack.plugin/src/com/ge/research/rack/RegenerateManifest.java

**Comment by saratge** [comment]
Changes are integrated into the main branch
Commit: https://github.com/ge-high-assurance/RITE/commit/1cd413e2649c062c8ce098825480474a99eb701e
