### ISSUE TITLE
Integrate the ARP4754 Plan Creator with the ARP4754A tool o RITE

### ISSUE THREAD

**Issue by pauls4GE** [ge-high-assurance/RITE#187]
Goal: Integrate the Plan generator and the Report Generator in the same RITE for an end-to-end-demo

Critera for completion:
- [x] Integrate the two tools together on one RITE instance
- [x] Add a button on RACK menu to invoke the Plan generator tool
- [x] Test on multiple use cases to check if everything is working
- - [x] All imports are correct
- - [x] All syntax is correct with respect to the examples
- - [x] Run the files on SADL to make sure the files compile (Saswata will help)  
- [x] Debug and confirm

Test Cases:
1. https://github.com/ge-high-assurance/FM_MBSE/tree/arp/ingestion/HEPS_arp_v1/Aircraft-DAP/ontology
2. https://github.com/ge-high-assurance/RITE/tree/arp4754/examples/ingestion-packages/OEM-Ingestion-Package-v3/OEM_ARP4754_Data/oem_arp4754_sadl_data/ontology (just the config and dap files)

**Comment by jshackleton** [comment]
One small detail: The "prefix" for the name of the generated SADL files and for the top URI alias is currently taken from the "systemAlias" configuration entry. For example, a "systemAlias" entry of "Aircraft" results in the top line of the DAP SADL file as:

`uri "http://sadl.org/aircraft_arp4754_dap.sadl" alias aircraftdap.`

Is this okay? Alternative, we could create a separate entry in the plan tool to represent this prefix.

**Comment by pauls4GE** [comment]
I think it will be helpful to let users add a custom filename if they want.

**Comment by pauls4GE** [comment]
@jshackleton , the ontology file for testing the second use case is https://github.com/ge-high-assurance/RITE/blob/arp4754/examples/ingestion-packages/OEM-Ingestion-Package-v3/OEM-Ontology/ontology/OEM.sadl

**Comment by jshackleton** [comment]
The branch I am working off of is `arp4754-plantool`, which is branched off of the `arp4754` branch.
