### ISSUE TITLE
"Ingest using Manifest File" only loads nodegroups with the filename query*.json

### ISSUE THREAD

**Issue by kityansiu** [ge-high-assurance/RITE#26]
@saratge @baoluomeng 

When using RITE and selecting the option "Ingest using Manifest File", the nodegroup ingestion part only loads nodegroups that have filename query*.json. For example, in Turnstile, this option will not load the nodegroup named GetDataInsertedByFromGuid.json, even though it's in the directory and is listed in store_data.csv correctly. The error message in the console is:

`[Worker-72: Ingesting data into RACK] ERROR com.ge.research.rack.utils.RackConsole - json file for query Get DataInsertedBy From Guidmissing in folder: C:\Users\200005944\eclipse-RITEworkspace$\Turnstile\nodegroups`

Note that "Upload Nodegroup(s)" and "Upload as Ingestion Package" options do not have this issue.

**Comment by saratge** [comment]
That particular nodegroup now gets ingested too
![image](https://user-images.githubusercontent.com/98990225/229246936-1694e7c1-84f2-472c-b480-01d055d489e7.png)

**Comment by saratge** [comment]
Fixed with https://github.com/ge-high-assurance/RITE/pull/39
