### ISSUE TITLE
"Ingest using Manifest File" should stop when there's an error

### ISSUE THREAD

**Issue by kityansiu** [ge-high-assurance/RITE#27]
@saratge @baoluomeng

When using RITE and selecting the option "Ingest using Manifest File", when there's an error in the data, the ingestion doesn't stop and so the user may miss the error reported in the console and think that everything is okay. 

Attached is a made-up ingestion package with data error embedded: [Turnstile.zip](https://github.com/ge-high-assurance/RITE/files/11021512/Turnstile.zip). Error is embedded in Turnstile\data\HazardAssessment\HAZARD_HAZARD*.csv, where the identifier "H-1" was changed to "H-1-nonsense" in both files.

Note that the RACK CLI stops on an error (`$ manifest import manifest.yaml`), as does the RACK UI page, as does the "Upload as Ingestion Package" option in RITE.

**Comment by saratge** [comment]
Thank you @kityansiu

**Comment by kityansiu** [comment]
While you're at it, consider changing the menu item from "Ingest using Manifest File" to "manifest load", which would align with the RACK CLI command.

**Comment by saratge** [comment]
Manifest Import now stops when there is an error, in the Erroneous Turnstile attached, it stops at Turnstile\data\HazardAssessment\HAZARD_HAZARD*.csv as mentioned, and prints the CSV file location where the failure occured
![image](https://user-images.githubusercontent.com/98990225/229247192-fb444f63-012d-4c10-becb-23a2492622bc.png)

**Comment by saratge** [comment]
Fixed with https://github.com/ge-high-assurance/RITE/pull/37
