### ISSUE TITLE
Separate consoles for RITE and SADL

### ISSUE THREAD

**Issue by baoluomeng** [ge-high-assurance/RITE#4]

**Comment by baoluomeng** [comment]
Ask John @tuxji if you have questions about how to use SADL API. Or maybe this is rather an Eclipse thing.

**Comment by saratge** [comment]
I have an alternative approach that need not use SADL API, that can programmatically pin the rack console
https://github.com/ge-high-assurance/RITE/blob/sarat-sprint-2/tools/rack/rack.plugin/src/com/ge/research/rack/views/ViewUtils.java#L105

We can pass the rack console object to pinConsole method 
By default RackConsole messages will be shown 
If needed the user can switch to SADL console

![image](https://user-images.githubusercontent.com/98990225/226995538-6b7c67a5-0561-4670-9d2a-5e0066eea061.png)
