### ISSUE TITLE
Uniform msgs printing

### ISSUE THREAD

**Issue by baoluomeng** [ge-high-assurance/RITE#5]

**Comment by baoluomeng** [comment]
Logger msgs should be in black color.

**Comment by baoluomeng** [comment]
The msgs from RACK/SemTK should be printed on RACK console. The msgs from SADL should be printed on SADL console. This is related to #4.

**Comment by saratge** [comment]
This is addressed in https://github.com/ge-high-assurance/RITE/commit/c385cf2f7b47dda4d17808c4a08975dc24846072
Info messages are printed in black and errors are printed in red
Fixes are also related to fixes for #4 
We now maintain separate consoles for SADL and Rack, by default the Rack Console is pinned
