### ISSUE TITLE
Finalize the demo story for the PI meeting

### ISSUE THREAD

**Issue by saratge** [ge-high-assurance/RITE#56]

**Comment by pauls4GE** [comment]
A video to give an idea about the demo story -- https://ge.box.com/s/vjvx1lhlf0jowjbikuj7eyjwg3wz1l2q

**Comment by saratge** [comment]
We have locked the demo story:

Demonstrate DO-178C Reporting feature in RITE 2 mins ? no export control data

             Checking compliance of SDP w.r.t to a specific PSAC given the specific OEM evidence 

Where did the data come from?

   - How does RITE help?  4 mins

      a. Makes assembly of ingestion package easier

          Before:  Use different sets of tools to put together ingestion package

                -   Trial-and-error to make sure packages are valid

         Now: RITE is one-stop shop to put together ingestion package

               -    Linting of manifest files, Ontology errors pre-ingestion: only SADL errors  

       b. Can any changes to evidence can be updated easily to RACK?  2 min

                -  Change data.yaml, demonstrate Manifest Import and show new DO 178C report 

          c. Also emphasize, generation of manifest and modular project structure 3min

          d. Emphasize existence of repo and wiki, point out the demo video 

       Right now at 11 mins
