### ISSUE TITLE
Configure data graphs to query against

### ISSUE THREAD

**Issue by baoluomeng** [ge-high-assurance/RITE#7]

**Comment by saratge** [comment]
A dialog opens when a nodegroup is selected for querying, showing a list of datagraphs.
By default, the datagraph from Rack Preference Page is selected.  The SemTK default graph is not selected by default, as the Turnstile ingestion package seems to use the data graph specified within the manifests. 
I assume this is the case with other ingestion packages. 
https://github.com/ge-high-assurance/RITE/commit/6bb47137ed2c1996aa6e055d2f1e697495074b1a
