### ISSUE TITLE
RITE should not identify non-SADL projects as SADL projects

### ISSUE THREAD

**Issue by pauls4GE** [ge-high-assurance/RITE#73]
Kit pointed out that RITE creates "ImplicitModel" and "OwlModels" subdirectories for any project. That should not be the case.

**Comment by saratge** [comment]
@pauls4GE @kityansiu RITE uses SADL eclipse as its base, it is the behavior of SADL eclipse
An

**Comment by pauls4GE** [comment]
@baoluomeng suggestion: Can we use Perspectives to turn the SADL behavior on and off?

**Comment by davidcok** [comment]
Not really -- Perspectives just define the locations and presence of a set of views.

The "Eclipse"  way is to use project natures.

**Comment by pauls4GE** [comment]
Actually, @davidcok , let me know if it is something you think you will be able to get done before the release. That would be wonderful!!

**Comment by davidcok** [comment]
@Pauls4GE or @chrisage - I'm going to need a bit of help here -- The RITE source code I'm using (from the repo) appears to be just a plugin on top of Eclipse. It does not have obvious references to SADL. I'd also need examples of SADL projects and non-SADL projects.

**Comment by saratge** [comment]
@davidcok  We reference SADL in targetplatform : https://github.com/ge-high-assurance/RITE/blob/main/tools/rack/rack.targetplatform/rack.targetplatform.target#L49-L52

**Comment by pauls4GE** [comment]
Must do as part of https://github.com/ge-high-assurance/RITE/issues/87
