### ISSUE TITLE
RITE Incomplete Error Messages on Ingestion Failures

### ISSUE THREAD

**Issue by pauls4GE** [ge-high-assurance/RITE#78]
**Background**:
RACK Actions (including upload manifest pictured below) do not capture full RACK output. Check all SDK action outputs match that of the CLI. RACK Validation Errors are also omitted from the console on upload.
<img width="523" alt="image" src="https://github.com/ge-high-assurance/RITE/assets/44778536/c39c6e4b-7f68-45a1-bbb5-dde69c889498">

**Acceptance Criteria**:
Check all SDK action outputs match that of the CLI

**Implementation Details**:

**Comment by chrisage** [comment]
@pauls4GE Would you be able to give a test example along with expected vs actual results?

**Comment by pauls4GE** [comment]
@chrisage, @kityansiu knows how to use the CLI better than I do. Can you coordinate with her and find out what would be the best way to address this?

**Comment by saratge** [comment]
@chrisage  Turnstile example should serve as a sufficient example

**Comment by saratge** [comment]
Here are a few ingestion packages:

[gsn_demo.zip](https://github.com/ge-high-assurance/RITE/files/12253345/gsn_demo.zip)
[Turnstile-missing-owl-references.zip](https://github.com/ge-high-assurance/RITE/files/12253358/Turnstile-missing-owl-references.zip)
[Turnstile-csv-error.zip](https://github.com/ge-high-assurance/RITE/files/12253362/Turnstile-csv-error.zip)

Test approach:
- Run rack cli manifest import --clear  command on these ingestion packages
- Observe both progress messages and error messages
- Align the progress messages and error messages that rack cli shows with RackConsole in RITE

**Comment by pauls4GE** [comment]
> 

@chrisage, apart from the issues Sarat mentioned, there can be other error messages. I think @kityansiu is the best resource for this. 

And we now have a comprehensive OEM ingestion package for RITE that includes stuff for features like GSN and DO178C https://github.com/ge-high-assurance/RITE/tree/main/examples/ingestion-packages/OEM-Ingestion-Package

**Comment by saratge** [comment]
This issue must be fixed now with PR: https://github.com/ge-high-assurance/RITE/pull/117
