### ISSUE TITLE
Clear Data Graph and Ingestion Data without modifying the Current RACK Data Model

### ISSUE THREAD

**Issue by pauls4GE** [ge-high-assurance/RITE#79]
**Background**:
For rapid data development, the user should be able to clear data without clearing the data models. This would enable them to load data immediately after without having to re-load the data models.

**Acceptance Criteria**:

**Implementation Details**:

**Comment by chrisage** [comment]
Related to #9

**Comment by chrisage** [comment]
Duplicate to #9. Closing as duplicate & capturing details in #9
