### ISSUE TITLE
Save Ingestion Package as ZIP Without Uploading

### ISSUE THREAD

**Issue by pauls4GE** [ge-high-assurance/RITE#81]
**Background**:
The user should be able to distribute ingestion packages without uploading to RACK

**Acceptance Criteria**:
A user should be able to distribute ingestion packages without uploading to RACK.

**Implementation Details**:
The "Upload as Ingestion Package" (right-click) action item should be separated into 2 separate actions:

- Upload as Ingestion Package - zips the ingestion package to a temp dir and uploads the package (deleting the package afterwards)
- Save Ingestion Package as Zip - prompts the user for a save location before zipping the package

**Comment by pauls4GE** [comment]
Just keep it simple where the "Manifest Import" function simply places the zip a temp location (without user choice) and uploads it and add a new "Save as Zip" option that opens up the file explorer for user to choose a location

**Comment by davidcok** [comment]
The referenced code is part of the "Upload as Ingestion Package" context-menu command (not the "Manifest Import").

I suggest splitting the command into two (with two menu items) one that does an upload through a temporary zip and one that produces a (non-temporary) zip without upload.

**Comment by pauls4GE** [comment]
> The referenced code is part of the "Upload as Ingestion Package" context-menu command (not the "Manifest Import").
> 
> I suggest splitting the command into two (with two menu items) one that does an upload through a temporary zip and one that produces a (non-temporary) zip without upload.

My mistake. I have fixed my comment up there. I support your suggestion. @chrisage , maybe @davidcok can also take care of this issue for you if the code is understandable enough for him to jump in.

**Comment by chrisage** [comment]
> My mistake. I have fixed my comment up there. I support your suggestion. @chrisage , maybe @davidcok can also take care of this issue for you if the code is understandable enough for him to jump in.

Thinking about this more, when I test my ingestion package I want it to upload (to make sure it works), and then I want to take that same package and distribute it (because I know it works)

**Comment by pauls4GE** [comment]
Closing as copy of #95
