### ISSUE TITLE
Ability to Clear RACK Components & Data on More Granular Level

### ISSUE THREAD

**Issue by baoluomeng** [ge-high-assurance/RITE#9]
**Background:** 
We want to be able to remove elements of our ingestion package in the RACK hosted instance to enable iterative development e.g. re-running scripts, fixing data etc. - For rapid data development, the user should be able to clear data without clearing the data models. This would enable them to load data immediately after without having to re-load the data models.

**Acceptance Criteria:**
From RITE all of the following should be enabled
1. Clear model graph (onotology)
2. Clear data graph (instance data)
3. Clear all nodegroups
4. Clear Data Graph and Ingestion Data without modifying the Current RACK Data Model 

**Implementation Details:**
- On a setting panel, we list all the data graphs, models, and all nodegroups that are currently available on SemTK. Then allow users to choose which ones to delete and save the settings.
- When user click on "Clear RACK", it will delete the user's selection

-- or --
- Within the respective views (nodegroups, data etc.) have a right click menu to clear individual data / nodegroups

**Comment by baoluomeng** [comment]
We need SemTK API to support this functionality. The idea is to give user the flexibility to choose the granularity to delete from SemTK. For example, they can choose to delete ontologies only, specific data/model graphs or any combination thereof. @weisenje

**Comment by chrisage** [comment]
Meeting Notes 3/14:
Performance gain in deleting all nodegroups at once - no performance gain expected in batch vs singly deletion - new API is for delete all only

**Comment by pauls4GE** [comment]
@chrisage, is this subsumed by #79 ? We should be able to delete data and model graphs selectively using options

**Comment by saratge** [comment]
### RACK CLI Commands to clear data, ontologies and nodegroups

### Clear data graph

Data can be cleared from RACK by graph name. Use `--data-graph` to override the
default `http://rack001/data`. Multiple data graphs can be specified.

```shell
(venv) $ rack data clear
(venv) $ rack data clear --data-graph http://rack001/Example
(venv) $ rack data clear --data-graph http://rack001/ex1 --data-graph http://rack001/ex2
```


When in doubt, use help option from rack cli as
```shell
rack data --help
rack data clear --help
```

### Clear model graph

All the Model can be cleared from RACK by graph name. Use `--model-graph` to  specify the model graph to clear
If no model graph is specified all the models all cleared

```shell
(venv) $ rack model clear
(venv) $ rack model clear --model-graph http://rack001/model

```
When in doubt, use help at the level of rack model clear as:
```shell
rack model clear --help
```

### Clear nodegroups

Nodegroups can be cleared entirely or individually with a specified nodegroup id

```shell
(venv) $ rack nodegroups delete-all
(venv) $ rack nodegroups delete somenodegroupId
```
When in doubt, use help option from rack cli as
```shell
rack nodegroups --help
rack nodegroups delete --help
```

RITE should now follow this behavior with a settings panel where a user can check different items : ontologies ,data, nodegroups to be cleared from RACK

One Way to test behavior:
   -  Nodegroups can be checked on SparqlGraph before and after deletion
   -  Ontologies : Check triple counts that shows the model graphs, data graphs with triple counts by clicking on RITE refresh 
                             button before and after deletion 
   - Data: Check triple counts using RITE refresh button similar to testing Ontologies

**Comment by pauls4GE** [comment]
NEED
- [ ] Ability to clear data graphs by user's choice: list all data graphs with a checkmark button to select the ones that must be deleted
- [ ] Ability to clear model graphs by user's choice: list all model graphs with a checkmark button to select the ones that must be deleted
- [ ] Make the "Clear RACK" button open a panel
- [ ] In the panel:
- - [ ] List all data graphs and model graphs with a checkmark infront of each (Also add a select all button)
- - [ ] A check mark to "Delete all nodegroups"
- - [ ] A super checkbox to select everything on RACK 
- - [ ] Add the "refresh" button to the Panel just to sync

**Comment by saratge** [comment]
Got confirmation from Paul C. that there is no way to distinguish model graphs from data graphs, we let the user specify which graphs to clear as a model graph or a data graph similar to rack cli.
