### ISSUE TITLE
Querying multiple nodegroups generates the result for only the first nodegroup selected

### ISSUE THREAD

**Issue by pauls4GE** [ge-high-assurance/RITE#90]
![image](https://github.com/ge-high-assurance/RITE/assets/66636651/3a7394c1-44e5-47a4-ad9b-81f04f2d12cc)

When multiple nodegroups are selected for querying, only the first nodegroup selected is executed. So maybe just remove the "(s)" from the "Query Nodegroup(s)" button that appears on right clicking? I can write this in the wiki

**Comment by pauls4GE** [comment]
@davidcok figure out the best possible way to deal with this

**Comment by davidcok** [comment]
Fixed with the merge of PR #106
