### ISSUE TITLE
Make the ontology info and nodegroup view table fit the entire panel

### ISSUE THREAD

**Issue by pauls4GE** [ge-high-assurance/RITE#94]
**Background**:
The nodegroup view table and ontology tables have fixed sizing and do not fill their parent panels and do not scale/respond to panel size changes.

![image](https://github.com/ge-high-assurance/RITE/assets/66636651/eca193e9-f2e7-4a82-aacb-2e1bf280e70d)

**Acceptance Criteria**:
Both the nodegroup view and ontology panel tables should scale (responsively) with panel size.

**Implementation Details**:

**Comment by davidcok** [comment]
@pauls4GE @chrisage The Nodegroup View uses a SWT Table widget, which is quite limited -- e.g. it only holds test and does not permit line wrapping in the cells. Also it does not scale nicely with changes in View size.

So the solution is probably to customize a generic Grid widget. That is a bit of work, but I'll start in on it unless you say it is not worth the trouble.
