### ISSUE TITLE
Potential crashing bug: unboxing of null Integer

### ISSUE THREAD

**Issue by davidcok** [ge-high-assurance/RITE#97]
In PsacDataProcessorBoeing.java, two uses of Integer indexofExistingObjective occur where they are unboxed to an int, but are definitely null -- so the code will crash if this branch is ever executed. Alternatively this if-branch is dead code and should be deleted

**Comment by pauls4GE** [comment]
Ignore this for now. This is a part of the experimental features. This is not part of any main release.
