### ISSUE TITLE
Check Wiki

### ISSUE THREAD

**Issue by pauls4GE** [ge-high-assurance/RITE#98]
Check the wiki to make sure that the instructions are understandable and unambiguous.

**Comment by pauls4GE** [comment]
Kindly check the following:
- [ ] The links work
- [ ] The instructions make sense

**Comment by davidcok** [comment]
- Add a page with some basic description of terminology: ontologies, nodegroups, instance data, properties, data graps, GSN, terminology about GSN, SADL/RACK/RITE
- Add a page describing the textual format of a yaml manifest file
- It is not clear what the organizational formal ofr an ingestion package needs to be -- or if it matters
- The page https://github.com/ge-high-assurance/RITE/wiki/RACK-Ingestion is out of date (though the behavior of uploads is an open Issue)
- Update the screen shots or menus on https://github.com/ge-high-assurance/RITE/wiki/RACK-Ingestion

**Comment by pauls4GE** [comment]
> 

Thanks @davidcok. I will address all of these, except the organizational format of the manifests since that is something only few people in the RACK team can explain and other users just copy existing ones and move from there. So it is expected that users should be familiar with RACK before they come to use RITE (I know that it is counterintuitive, but that is how it is).
